export const moduleConfigs = {
  students: {
    title: "Students",
    singular: "Student",
    addLabel: "Add Student",
    searchPlaceholder: "Search student by name, class, status...",
    columns: [
      { key: "name", label: "Name" },
      { key: "className", label: "Class" },
      { key: "section", label: "Section" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { name: "name", label: "Student Name" },
      { name: "className", label: "Class" },
      { name: "section", label: "Section" },
      { name: "status", label: "Status", type: "select", options: ["Active", "Inactive"] },
    ],
    initialRows: [
      { id: 1, name: "Ayaan Rahman", className: "Class 6", section: "A", status: "Active" },
      { id: 2, name: "Mahi Ahmed", className: "Class 8", section: "B", status: "Active" },
      { id: 3, name: "Sadia Anjum", className: "Class 6", section: "B", status: "Inactive" },
    ],
  },
  teachers: {
    title: "Teachers",
    singular: "Teacher",
    addLabel: "Add Teacher",
    searchPlaceholder: "Search teacher by name, subject, status...",
    columns: [
      { key: "name", label: "Name" },
      { key: "subject", label: "Subject" },
      { key: "designation", label: "Designation" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { name: "name", label: "Teacher Name" },
      { name: "subject", label: "Subject" },
      { name: "designation", label: "Designation" },
      { name: "status", label: "Status", type: "select", options: ["Active", "Inactive"] },
    ],
    initialRows: [
      { id: 1, name: "Md. Fahim Hasan", subject: "Math", designation: "Senior Teacher", status: "Active" },
      { id: 2, name: "Nusrat Jahan", subject: "English", designation: "Assistant Teacher", status: "Active" },
      { id: 3, name: "Rafiq Islam", subject: "Physics", designation: "Lecturer", status: "Inactive" },
    ],
  },
  parents: {
    title: "Parents",
    singular: "Parent",
    addLabel: "Add Parent",
    searchPlaceholder: "Search parent by name, student, status...",
    columns: [
      { key: "name", label: "Parent Name" },
      { key: "student", label: "Student" },
      { key: "phone", label: "Phone" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { name: "name", label: "Parent Name" },
      { name: "student", label: "Student Name" },
      { name: "phone", label: "Phone" },
      { name: "status", label: "Status", type: "select", options: ["Active", "Inactive"] },
    ],
    initialRows: [
      { id: 1, name: "Nusrat Jahan", student: "Ayaan Rahman", phone: "+8801711000001", status: "Active" },
      { id: 2, name: "Rafiq Ahmed", student: "Mahi Ahmed", phone: "+8801711000002", status: "Active" },
      { id: 3, name: "Parvin Sultana", student: "Sadia Anjum", phone: "+8801711000003", status: "Inactive" },
    ],
  },
  classes: {
    title: "Classes",
    singular: "Class",
    addLabel: "Add Class",
    searchPlaceholder: "Search class by name, section, status...",
    columns: [
      { key: "name", label: "Class" },
      { key: "section", label: "Section" },
      { key: "teacher", label: "Class Teacher" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { name: "name", label: "Class Name" },
      { name: "section", label: "Section" },
      { name: "teacher", label: "Class Teacher" },
      { name: "status", label: "Status", type: "select", options: ["Active", "Inactive"] },
    ],
    initialRows: [
      { id: 1, name: "Class 6", section: "A", teacher: "Md. Fahim Hasan", status: "Active" },
      { id: 2, name: "Class 7", section: "B", teacher: "Nusrat Jahan", status: "Active" },
      { id: 3, name: "Class 8", section: "C", teacher: "Rafiq Islam", status: "Inactive" },
    ],
  },
  subjects: {
    title: "Subjects",
    singular: "Subject",
    addLabel: "Add Subject",
    searchPlaceholder: "Search subject by name, code, status...",
    columns: [
      { key: "name", label: "Subject" },
      { key: "code", label: "Code" },
      { key: "className", label: "Class" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { name: "name", label: "Subject Name" },
      { name: "code", label: "Subject Code" },
      { name: "className", label: "Class" },
      { name: "status", label: "Status", type: "select", options: ["Active", "Inactive"] },
    ],
    initialRows: [
      { id: 1, name: "Mathematics", code: "MTH-101", className: "Class 6", status: "Active" },
      { id: 2, name: "Physics", code: "PHY-201", className: "Class 8", status: "Active" },
      { id: 3, name: "History", code: "HIS-103", className: "Class 7", status: "Inactive" },
    ],
  },
  attendance: {
    title: "Attendance",
    singular: "Attendance Record",
    addLabel: "Add Attendance",
    searchPlaceholder: "Search attendance by class, date, status...",
    columns: [
      { key: "className", label: "Class" },
      { key: "date", label: "Date" },
      { key: "present", label: "Present" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { name: "className", label: "Class" },
      { name: "date", label: "Date", type: "date" },
      { name: "present", label: "Present Count", type: "number" },
      { name: "status", label: "Status", type: "select", options: ["Active", "Inactive"] },
    ],
    initialRows: [
      { id: 1, className: "Class 6", date: "2026-03-10", present: 38, status: "Active" },
      { id: 2, className: "Class 7", date: "2026-03-10", present: 35, status: "Active" },
      { id: 3, className: "Class 8", date: "2026-03-10", present: 31, status: "Inactive" },
    ],
  },
  fees: {
    title: "Fees",
    singular: "Fee",
    addLabel: "Add Fee",
    searchPlaceholder: "Search fee by student, month, status...",
    columns: [
      { key: "student", label: "Student" },
      { key: "month", label: "Month" },
      { key: "amount", label: "Amount" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { name: "student", label: "Student Name" },
      { name: "month", label: "Month" },
      { name: "amount", label: "Amount", type: "number" },
      { name: "status", label: "Status", type: "select", options: ["Active", "Inactive"] },
    ],
    initialRows: [
      { id: 1, student: "Ayaan Rahman", month: "March", amount: 120, status: "Active" },
      { id: 2, student: "Mahi Ahmed", month: "March", amount: 120, status: "Active" },
      { id: 3, student: "Sadia Anjum", month: "March", amount: 120, status: "Inactive" },
    ],
  },
  exams: {
    title: "Exams",
    singular: "Exam",
    addLabel: "Add Exam",
    searchPlaceholder: "Search exam by name, class, status...",
    columns: [
      { key: "name", label: "Exam" },
      { key: "className", label: "Class" },
      { key: "date", label: "Date" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { name: "name", label: "Exam Name" },
      { name: "className", label: "Class" },
      { name: "date", label: "Date", type: "date" },
      { name: "status", label: "Status", type: "select", options: ["Active", "Inactive"] },
    ],
    initialRows: [
      { id: 1, name: "Mid-Term", className: "Class 6", date: "2026-04-15", status: "Active" },
      { id: 2, name: "Final", className: "Class 7", date: "2026-10-20", status: "Active" },
      { id: 3, name: "Weekly Test", className: "Class 8", date: "2026-03-20", status: "Inactive" },
    ],
  },
  timetable: {
    title: "Timetable",
    singular: "Timetable",
    addLabel: "Add Timetable",
    searchPlaceholder: "Search timetable by class, day, status...",
    columns: [
      { key: "className", label: "Class" },
      { key: "day", label: "Day" },
      { key: "period", label: "Period" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { name: "className", label: "Class" },
      { name: "day", label: "Day" },
      { name: "period", label: "Period" },
      { name: "status", label: "Status", type: "select", options: ["Active", "Inactive"] },
    ],
    initialRows: [
      { id: 1, className: "Class 6", day: "Monday", period: "08:00 - 09:00", status: "Active" },
      { id: 2, className: "Class 7", day: "Tuesday", period: "09:00 - 10:00", status: "Active" },
      { id: 3, className: "Class 8", day: "Wednesday", period: "10:00 - 11:00", status: "Inactive" },
    ],
  },
  library: {
    title: "Library",
    singular: "Book",
    addLabel: "Add Book",
    searchPlaceholder: "Search books by title, category, status...",
    columns: [
      { key: "name", label: "Book" },
      { key: "category", label: "Category" },
      { key: "quantity", label: "Quantity" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { name: "name", label: "Book Title" },
      { name: "category", label: "Category" },
      { name: "quantity", label: "Quantity", type: "number" },
      { name: "status", label: "Status", type: "select", options: ["Active", "Inactive"] },
    ],
    initialRows: [
      { id: 1, name: "Science 101", category: "Science", quantity: 42, status: "Active" },
      { id: 2, name: "English Grammar", category: "Language", quantity: 30, status: "Active" },
      { id: 3, name: "World History", category: "History", quantity: 18, status: "Inactive" },
    ],
  },
  transport: {
    title: "Transport",
    singular: "Route",
    addLabel: "Add Route",
    searchPlaceholder: "Search route by name, driver, status...",
    columns: [
      { key: "name", label: "Route" },
      { key: "vehicle", label: "Vehicle" },
      { key: "driver", label: "Driver" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { name: "name", label: "Route Name" },
      { name: "vehicle", label: "Vehicle Number" },
      { name: "driver", label: "Driver Name" },
      { name: "status", label: "Status", type: "select", options: ["Active", "Inactive"] },
    ],
    initialRows: [
      { id: 1, name: "North Route", vehicle: "DHK-1234", driver: "Kamal Uddin", status: "Active" },
      { id: 2, name: "City Route", vehicle: "DHK-5678", driver: "Jamal Hossain", status: "Active" },
      { id: 3, name: "South Route", vehicle: "DHK-9001", driver: "Rana Mia", status: "Inactive" },
    ],
  },
  hostel: {
    title: "Hostel",
    singular: "Room",
    addLabel: "Add Room",
    searchPlaceholder: "Search room by block, floor, status...",
    columns: [
      { key: "name", label: "Room" },
      { key: "block", label: "Block" },
      { key: "capacity", label: "Capacity" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { name: "name", label: "Room Number" },
      { name: "block", label: "Block" },
      { name: "capacity", label: "Capacity", type: "number" },
      { name: "status", label: "Status", type: "select", options: ["Active", "Inactive"] },
    ],
    initialRows: [
      { id: 1, name: "A-101", block: "Block A", capacity: 6, status: "Active" },
      { id: 2, name: "B-202", block: "Block B", capacity: 8, status: "Active" },
      { id: 3, name: "C-303", block: "Block C", capacity: 4, status: "Inactive" },
    ],
  },
  notices: {
    title: "Notices",
    singular: "Notice",
    addLabel: "Add Notice",
    searchPlaceholder: "Search notices by title, audience, status...",
    columns: [
      { key: "title", label: "Title" },
      { key: "audience", label: "Audience" },
      { key: "date", label: "Date" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { name: "title", label: "Notice Title" },
      { name: "audience", label: "Audience" },
      { name: "date", label: "Date", type: "date" },
      { name: "status", label: "Status", type: "select", options: ["Active", "Inactive"] },
    ],
    initialRows: [
      { id: 1, title: "Holiday Announcement", audience: "All", date: "2026-03-21", status: "Active" },
      { id: 2, title: "Exam Schedule", audience: "Students", date: "2026-04-01", status: "Active" },
      { id: 3, title: "Fee Reminder", audience: "Parents", date: "2026-03-15", status: "Inactive" },
    ],
  },
  reports: {
    title: "Reports",
    singular: "Report",
    addLabel: "Add Report",
    searchPlaceholder: "Search reports by title, type, status...",
    columns: [
      { key: "title", label: "Report" },
      { key: "type", label: "Type" },
      { key: "generatedBy", label: "Generated By" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { name: "title", label: "Report Title" },
      { name: "type", label: "Type" },
      { name: "generatedBy", label: "Generated By" },
      { name: "status", label: "Status", type: "select", options: ["Active", "Inactive"] },
    ],
    initialRows: [
      { id: 1, title: "Attendance Summary", type: "Attendance", generatedBy: "Admin", status: "Active" },
      { id: 2, title: "Fee Collection", type: "Finance", generatedBy: "Accounts", status: "Active" },
      { id: 3, title: "Exam Analysis", type: "Academic", generatedBy: "Exam Cell", status: "Inactive" },
    ],
  },
  settings: {
    title: "Settings",
    singular: "Setting",
    addLabel: "Add Setting",
    searchPlaceholder: "Search settings by key, value, status...",
    columns: [
      { key: "name", label: "Setting" },
      { key: "value", label: "Value" },
      { key: "scope", label: "Scope" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { name: "name", label: "Setting Name" },
      { name: "value", label: "Value" },
      { name: "scope", label: "Scope" },
      { name: "status", label: "Status", type: "select", options: ["Active", "Inactive"] },
    ],
    initialRows: [
      { id: 1, name: "Academic Year", value: "2026", scope: "Global", status: "Active" },
      { id: 2, name: "Auto Attendance", value: "Enabled", scope: "Attendance", status: "Active" },
      { id: 3, name: "Payment Gateway", value: "Disabled", scope: "Finance", status: "Inactive" },
    ],
  },
};